[package]
name = "shadertoys-shaders"
version = "0.0.0"
authors = []
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
spirv-std.workspace = true
shared = { path = "../shared" }

[lints]
workspace = true
